#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Customize to your needs...
export ANDROID_HOME=/home/wxbin/develop/sdk
# export STUDIO_JDK=/home/wxbin/develop/java/jdk1.8.0_91
export ANDROID_SDK=$ANDROID_HOME
# gradle
export GRADLE_HOME=/home/wxbin/develop/gradle
export GRADLE_USER_HOME=/home/wxbin/.gradle
# android
ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools
ANDROID_TOOLS=$ANDROID_HOME/tools
# ndk
export NDK_HOME=/home/wxbin/develop/android-ndk-r10d
export NDK=$NDK_HOME
export ANDROID_NDK=$NDK_HOME

PATH=:$ANDROID_PLATFORM_TOOLS:$ANDROID_TOOLS:$GRADLE_HOME/gradle-3.3/bin:$NDK_HOME:$PATH
